"use client";

import type { CSSProperties } from "react";
import type { BrandTheme } from "@/lib/brand-theme";
import { T } from "./ui-primitives";

export interface FigmaExportButtonProps {
  ticker: string;
  brandName: string;
  theme: BrandTheme;
  palette: string[];
}

interface ColorToken {
  value: string;
  type: "color";
}

interface BorderRadiusToken {
  value: string;
  type: "borderRadius";
}

interface TokenStudioJson {
  color: {
    brand: Record<string, ColorToken>;
    palette: Record<string, ColorToken>;
  };
  border: {
    radius: Record<string, BorderRadiusToken>;
  };
}

function buildTokenStudioJson(
  ticker: string,
  theme: BrandTheme,
  palette: string[]
): string {
  const brandColors: Record<string, ColorToken> = {
    accent: { value: theme.accent, type: "color" },
    accentBright: { value: theme.accentBright, type: "color" },
    accentDim: { value: theme.accentDim, type: "color" },
    background: { value: theme.bg, type: "color" },
    surface: { value: theme.surface, type: "color" },
    surfaceLift: { value: theme.surfaceLift, type: "color" },
    text: { value: theme.text, type: "color" },
    textBright: { value: theme.textBright, type: "color" },
    textSecondary: { value: theme.textSecondary, type: "color" },
    textMuted: { value: theme.textMuted, type: "color" },
    border: { value: theme.border, type: "color" },
  };

  const paletteColors: Record<string, ColorToken> = {};
  palette.forEach((hex, i) => {
    paletteColors[`color${i}`] = { value: hex, type: "color" };
  });

  const tokens: TokenStudioJson = {
    color: {
      brand: brandColors,
      palette: paletteColors,
    },
    border: {
      radius: {
        base: { value: String(theme.radius), type: "borderRadius" },
        card: { value: String(theme.radius), type: "borderRadius" },
      },
    },
  };

  const header = `// Token Studio — ${ticker} Brand Tokens\n// Generated by Brand Autopsy DB\n`;
  return header + JSON.stringify(tokens, null, 2);
}

const btnStyle: CSSProperties = {
  display: "inline-flex",
  alignItems: "center",
  gap: 5,
  padding: "5px 9px",
  border: `1px solid ${T.border}`,
  borderRadius: 3,
  background: T.surface,
  color: T.text,
  fontFamily: T.mono,
  fontSize: 10,
  cursor: "pointer",
  letterSpacing: "0.06em",
};

const FigmaIcon = (): JSX.Element => (
  <svg
    width={12}
    height={12}
    viewBox="0 0 12 12"
    fill="currentColor"
    aria-hidden="true"
  >
    <rect x="0" y="0" width="5" height="5" rx="1" opacity="0.9" />
    <rect x="7" y="0" width="5" height="5" rx="1" opacity="0.6" />
    <rect x="0" y="7" width="5" height="5" rx="1" opacity="0.6" />
    <rect x="7" y="7" width="5" height="5" rx="1" opacity="0.3" />
  </svg>
);

export function FigmaExportButton({
  ticker,
  brandName: _brandName,
  theme,
  palette,
}: FigmaExportButtonProps): JSX.Element {
  const handleExport = (): void => {
    const json = buildTokenStudioJson(ticker, theme, palette);
    const blob = new Blob([json], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${ticker}-brand-tokens.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <button type="button" onClick={handleExport} style={btnStyle} aria-label="Export Figma tokens">
      <FigmaIcon /> FIGMA
    </button>
  );
}
